baseURL: "https://mrbayat.netlify.app"
languageCode: "en-us"
title: "Mohammad Reza Bayat"
theme: "./.."
relativeURLs: true

googleanalytics: UA-xxxxxx-x
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

  favicon: "/images/fav.png"
  description: "Persoanl website of Dr. Mohammad Reza Bayat."

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"

  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Mohammad Reza Bayat"
  profession: "a computational mechanics researcher."
  github: "https://github.com/mrezabayat"
  linkedin: "https://linkedin.com/in/mrbayat"
  instagram: "https://www.instagram.com/mrebayat/"
  # twitter: "https://twitter.com/"
  # facebook: "https://facebook.com"

  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm Mohammad Reza Bayat, a passionate computational mechanics researcher. I tend to utilize modern numerical techniques to simulate the behavior of various materials and optimum product design."
  descripe_l2_person: "Currently, I am developing high-performance software in parallel using C++ for fitted and unfitted isogeometric analysis. I enjoy working independently as much as in a multi-disciplinary team."
  skills:
    - name: Isogeometric Analysis
      percentage: 90
    - name: Finite Element Method
      percentage: 95
    - name: C++
      percentage: 80
    - name: High-performance Computing
      percentage: 75

  # Experience
  disable_experience: false
  experience:
    - company: "BarcelonaTech"
      role: "Software developer"
      startdate: Feb 2021
      enddate: present
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Facebook"
      role: "Fullstack developer"
      startdate: Mar 2020
      enddate: Dec 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Amazon"
      role: "Fullstack developer"
      startdate: Feb 2019
      enddate: Jan 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.

  # Education
  disable_education: false
  education:
    - degree: "PhD"
      branch: "Mechanical Engineering"
      university: "University of Tehran"
      startedyear: "2013"
      graduation: "2018"
    - degree: "Degree"
      branch: "Branch"
      university: "Example university"
      startedyear: "year"
      graduation: "year"
    - degree: "Degree"
      branch: "Branch"
      university: "Example university"
      startedyear: "year"
      graduation: "year"

  # Projects
  disable_projects: false
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: false
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "example@mail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
