baseURL: "https://mrbayat.netlify.app"
languageCode: "en-us"
title: "Mohammad Reza Bayat"
theme: "./.."
relativeURLs: true

googleanalytics: UA-xxxxxx-x
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

  favicon: "/images/fav.png"
  description: "Persoanl website of Dr. Mohammad Reza Bayat."

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"

  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Mohammad Reza Bayat"
  profession: "a computational mechanics researcher."
  github: "https://github.com/mrezabayat"
  linkedin: "https://linkedin.com/in/mrbayat"
  instagram: "https://www.instagram.com/mrebayat/"
  # twitter: "https://twitter.com/"
  # facebook: "https://facebook.com"

  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm Mohammad Reza Bayat, a passionate computational mechanics researcher. I tend to utilize modern numerical techniques to simulate the behavior of various materials and optimum product design."
  descripe_l2_person: "Currently, I am developing high-performance software in parallel using C++ for fitted and unfitted isogeometric analysis. I enjoy working independently as much as in a multi-disciplinary team."
  skills:
    - name: Isogeometric Analysis
      percentage: 90
    - name: Finite Element Method
      percentage: 95
    - name: C++
      percentage: 80
    - name: High-performance Computing
      percentage: 75

  # Experience
  disable_experience: false
  experience:
    - company: "BarcelonaTech"
      role: "Simulation Software Developer"
      startdate: Aug 2020
      enddate: present
      featuredpoints:
        - point: Programming trimmed isogeometric analysis in an MPI-based parallel C++ library.
        - point: Modeling multiscale and muliphysics Flexoelectricity (higher-order nonlinear coupled PDE).
        - point: Developing and bringing new physics insights of flexoelectric metamaterials which are to be published in a highly reputed journal of mechanics.
        - point: Documenting and presenting the results of simulations to the people in the group.
    - company: "MAPNA"
      role: "R&D Mechanical Engineer"
      startdate: Oct 2016
      enddate: Aug 2020
      featuredpoints:
        - point: Static Structural, Modal and Harmonic analysis of components using numerical methods.
        - point: Automatic FEA employing ANSYS Customization Toolkit (ACT).
        - point: Electrical, thermal, mechanical, and fluid-solid interaction analysis.

  # Education
  disable_education: false
  education:
    - degree: "PhD"
      branch: "Mechanical Engineering"
      university: "University of Tehran - Overall GPA: 18.24/20"
      startedyear: "2015"
      graduation: "2019"
    - degree: "Master"
      branch: "Mechanical Engineering"
      university: "University of Tehran - Overall GPA: 18.68/20"
      startedyear: "2013"
      graduation: "2015"
    - degree: "Bachelor"
      branch: "Mechanical Engineering"
      university: "Zanjan University - Overall GPA: 18.21/20"
      startedyear: "2009"
      graduation: "2013"

  # Projects
  disable_projects: false
  projects:
    - name: "HIgh PERformance LIbrary for Finite Element (hiperlife)"
      img: /images/logo_wtitle_white.svg
      githublink: "https://git.lacan.upc.edu/HPLFEgroup"
      featuredlink: "/"
      description: "hiperlife is a high performance parallel library for finite elements. The aim of this library is to provide a computational framework to address problems of cell and tissue mechanobiology for a wide range of cases and users, with special focus on curved surfaces (the cell membrane, the cell cortex, epithelial monolayers,etc.). It is designed to handle the multiphysic nature of problems in mechanobiology, to manage unstructured grids that deal with complex geometries and to allow arbitrary higher-order basis functions that describe the curvature of interfaces. hiperlife is written in C++, uses the Message Passage Interface (MPI) paradigm for parallelism, and is built on top of several packages of the Trilinos Project. These particular choices set the basis for the main features of the library, namely, parallelism, flexibility, user-centered design and sustainability."

  # Achievements
  disable_achievements: false
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "example@mail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
